server:
  port: 8081

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/CeroHex/springboot_microserviciosvehiculos
          default-label: master              # Asegúrate que 'main' es la rama correcta
          search-paths:
            - config-data                 # Asegúrate que esta carpeta existe en el repo
