server:
  port: 8081

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/CeroHex/springboot_microserviciosvehiculos
          search-paths: config-data
